name: countup
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  barcode_scan2: ^4.2.4
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  freezed: ^2.2.0
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_annotation: ^4.8.1
  logger: any  #for logging purpose
  retrofit: '>=4.0.0 <5.0.0'
  webview_flutter: ^4.2.0


dev_dependencies:
  build_runner: '>=2.3.0 <4.0.0'
  freezed_annotation: ^2.2.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  pedantic_mono: any
  retrofit_generator: '>=5.0.0 <6.0.0'


flutter:
  uses-material-design: true
