name: countup
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  barcode_scan2: ^4.2.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  webview_flutter: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true
